"""Add map usage tracking table

Revision ID: fb57e57021a7
Revises: 
Create Date: 2025-07-11 18:34:37.419354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb57e57021a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_usage_events_created_at'), 'map_usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_map_usage_events_event_type'), 'map_usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_map_usage_events_session_id'), 'map_usage_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_map_usage_events_timestamp'), 'map_usage_events', ['timestamp'], unique=False)
    op.create_index('ix_map_usage_session_timestamp', 'map_usage_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('ix_map_usage_type_timestamp', 'map_usage_events', ['event_type', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_trends_calculation_date'), table_name='property_trends')
    op.drop_index(op.f('ix_trends_period_start'), table_name='property_trends')
    op.drop_index(op.f('ix_room_periods_current'), table_name='room_availability_periods')
    op.drop_index(op.f('ix_room_periods_dates'), table_name='room_availability_periods')
    op.drop_index(op.f('ix_room_periods_room_id'), table_name='room_availability_periods')
    op.drop_index(op.f('ix_price_history_detected_at'), table_name='room_price_history')
    op.drop_constraint(op.f('rooms_current_availability_period_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'room_availability_periods', ['current_availability_period_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_current_availability_period_id_fkey'), 'rooms', 'room_availability_periods', ['current_availability_period_id'], ['id'])
    op.create_index(op.f('ix_price_history_detected_at'), 'room_price_history', ['detected_at'], unique=False)
    op.create_index(op.f('ix_room_periods_room_id'), 'room_availability_periods', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_periods_dates'), 'room_availability_periods', ['period_start_date', 'period_end_date'], unique=False)
    op.create_index(op.f('ix_room_periods_current'), 'room_availability_periods', ['is_current_period'], unique=False)
    op.create_index(op.f('ix_trends_period_start'), 'property_trends', ['period_start'], unique=False)
    op.create_index(op.f('ix_trends_calculation_date'), 'property_trends', ['calculation_date'], unique=False)
    op.drop_index('ix_map_usage_type_timestamp', table_name='map_usage_events')
    op.drop_index('ix_map_usage_session_timestamp', table_name='map_usage_events')
    op.drop_index(op.f('ix_map_usage_events_timestamp'), table_name='map_usage_events')
    op.drop_index(op.f('ix_map_usage_events_session_id'), table_name='map_usage_events')
    op.drop_index(op.f('ix_map_usage_events_event_type'), table_name='map_usage_events')
    op.drop_index(op.f('ix_map_usage_events_created_at'), table_name='map_usage_events')
    op.drop_table('map_usage_events')
    # ### end Alembic commands ###
